on:
  workflow_dispatch:
#  schedule:
#    - cron: "0 * * * *"

name: Render Wisconsin

jobs:
  render:
    name: Render Wisconsin
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run:  Rscript -e 'install.packages(c("rmarkdown", "tidyverse", "jsonlite", "zoo", "lubridate", "ggrepel"))'
      - name: Render Wisconsin
        run:  Rscript -e 'rmarkdown::render("Reports/Wisconsin.Rmd", output_format = "html_document")'
      - name: Commit results
        run:  |
          git commit Reports/Wisconsin.Rmd -m 'Re-build Wisconsin.Rmd'
          git push origin
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: mail.hover.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.BLD_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.BLD_PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: jdjohn215@gmail.com
          # Required sender full name (address can be skipped):
          from: John Johnson # <user@example.com>
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
          # Optional attachments:
          attachments: updated_data.csv, Reports/Wisconsin.html
    